// ============================================================
// site-data.js — the property & destination content.
// Edit this file to change listings; every page reads from here.
// Mirrors src/data/properties.ts and src/data/destinations.ts
//
// Image paths below are bare filenames (e.g. "cat-forest.jpg").
// This file is loaded from the site root AND from /properties/ and
// /neighbourhoods/ subfolders, so use img() (defined at the bottom)
// wherever you need a working <img src>, rather than the raw field.
// ============================================================

const ASSET_PREFIX = /\/(properties|neighbourhoods)\//.test(window.location.pathname)
  ? "../assets/"
  : "assets/";

function img(name) {
  return ASSET_PREFIX + name;
}

const PROPERTIES = [
  {
    id: "the-forest-estate",
    name: "The Forest Estate",
    location: "Jim Corbett",
    region: "Uttarakhand",
    neighbourhood: "jim-corbett",
    collection: "forest",
    type: "Private Villa",
    priceLabel: "₹4.75 Cr onwards",
    priceCr: 4.75,
    builtUpSqft: 4200,
    landSqft: 12000,
    bedrooms: 4,
    developer: "Sal & Stone Estates",
    status: "Ready",
    availability: "6 residences of 24 remaining",
    verified: true,
    verifications: ["Project Verified", "Documentation Reviewed", "Developer Verified"],
    featured: true,
    lifestyle: ["Privacy", "Nature", "Wellness", "Rental potential"],
    amenities: ["Private plunge pool", "Forest deck", "Staff quarters", "Managed housekeeping", "Gated community", "Power back-up"],
    images: ["cat-forest.jpg", "prop-living.jpg", "prop-pool.jpg"],
    story: {
      idea: "A low, quiet house built to disappear into sal forest — designed so the trees, not the architecture, remain the subject.",
      setting: "Twelve thousand square feet of wooded land on the eastern edge of the Corbett landscape, with a seasonal stream along the boundary.",
      residence: "Four bedrooms across a single stepped level, local stone, lime plaster and teak joinery, with a double-height living volume opening to the deck.",
      experience: "Mornings on the deck with birdsong, afternoons indoors while the light moves, evenings around an outdoor fire. Housekeeping is arranged before you arrive.",
      community: "A 24-residence gated enclave with shared forest trails, a small clubhouse and on-site management for owners who visit intermittently.",
    },
    investment: { rentalNightly: 28000, occupancy: 34, appreciation: 8, lifestyleScore: 92, investmentScore: 84 },
  },
  {
    id: "the-quiet-ridge",
    name: "The Quiet Ridge",
    location: "Mukteshwar",
    region: "Uttarakhand",
    neighbourhood: "mukteshwar",
    collection: "mountains",
    type: "Mountain Residence",
    priceLabel: "₹3.40 Cr onwards",
    priceCr: 3.4,
    builtUpSqft: 3100,
    landSqft: 8500,
    bedrooms: 3,
    developer: "Ridgeline Developments",
    status: "Under Construction",
    availability: "Possession indicated 2027",
    verified: true,
    verifications: ["Project Verified", "Documentation Reviewed"],
    featured: true,
    lifestyle: ["Views", "Privacy", "Weekend escape"],
    amenities: ["Panoramic glazing", "Orchard land", "Wood-burning hearth", "Solar assist", "Caretaker residence"],
    images: ["cat-mountains.jpg", "prop-pool.jpg", "prop-living.jpg"],
    story: {
      idea: "A three-bedroom house placed along a single contour so every room faces the Himalayan skyline without terracing the hillside.",
      setting: "An east-facing ridge above Mukteshwar, surrounded by old pine and a small existing apple orchard.",
      residence: "Stone base, timber upper level, deep eaves and a long verandah designed for cold-weather sun.",
      experience: "Slow mornings above the cloud line, walking distance to the temple ridge, and a village market twenty minutes away.",
      community: "Nine independent plots with shared access road, water infrastructure and estate maintenance.",
    },
    investment: { rentalNightly: 22000, occupancy: 30, appreciation: 9, lifestyleScore: 88, investmentScore: 80 },
  },
  {
    id: "the-river-sanctuary",
    name: "The River Sanctuary",
    location: "Rishikesh",
    region: "Uttarakhand",
    neighbourhood: "rishikesh",
    collection: "wellness",
    type: "Wellness Estate",
    priceLabel: "₹6.20 Cr onwards",
    priceCr: 6.2,
    builtUpSqft: 4800,
    landSqft: 14000,
    bedrooms: 4,
    developer: "Ganga Valley Estates",
    status: "Ready",
    availability: "3 residences available",
    verified: true,
    verifications: ["Project Verified", "Documentation Reviewed", "Developer Verified"],
    featured: true,
    lifestyle: ["Wellness", "Hospitality", "Privacy", "Rental potential"],
    amenities: ["Yoga pavilion", "Therapy room", "Reflecting pool", "Hospitality-managed service", "Organic kitchen garden"],
    images: ["cat-wellness.jpg", "prop-living.jpg", "prop-pool.jpg"],
    story: {
      idea: "A residence organised around stillness — water, shade and a single long axis toward the river valley.",
      setting: "A terraced slope above the Ganga, with mist most mornings and forest behind.",
      residence: "Four suites, a covered wellness pavilion and a shaded courtyard, in pale stone and deep green joinery.",
      experience: "Practice at dawn, treatments arranged on request, meals from the garden, and the river within walking reach.",
      community: "Operated with a hospitality partner, giving owners serviced use and optional managed rental when away.",
    },
    investment: { rentalNightly: 42000, occupancy: 44, appreciation: 9, lifestyleScore: 94, investmentScore: 89 },
  },
  {
    id: "the-country-house",
    name: "The Country House",
    location: "Sohna",
    region: "Haryana",
    neighbourhood: "sohna",
    collection: "countryside",
    type: "Farmhouse",
    priceLabel: "₹2.85 Cr onwards",
    priceCr: 2.85,
    builtUpSqft: 3400,
    landSqft: 43560,
    bedrooms: 3,
    developer: "Aravalli Land Co.",
    status: "Ready",
    availability: "Acre plots with built residence",
    verified: true,
    verifications: ["Project Verified", "Documentation Reviewed"],
    featured: true,
    lifestyle: ["Family", "Accessibility", "Weekend escape"],
    amenities: ["One acre of land", "Orchard", "Pool", "Covered verandah", "Staff quarters"],
    images: ["cat-country.jpg", "prop-living.jpg", "prop-pool.jpg"],
    story: {
      idea: "An hour from Gurugram: a low country house on a full acre, built for Friday evenings rather than annual holidays.",
      setting: "Open farmland at the foot of the Aravallis, with old neem and jamun trees retained.",
      residence: "Three bedrooms, a long shaded verandah, brick and lime finishes, and a service court.",
      experience: "Close enough for a single night away. Kitchen gardens, a pool for summer, and space for twenty people at a table.",
      community: "A cluster of eleven farm parcels with shared boundary security and estate upkeep.",
    },
    investment: { rentalNightly: 18000, occupancy: 26, appreciation: 7, lifestyleScore: 84, investmentScore: 78 },
  },
  {
    id: "the-pine-pavilion",
    name: "The Pine Pavilion",
    location: "Kasauli",
    region: "Himachal Pradesh",
    neighbourhood: "kasauli",
    collection: "mountains",
    type: "Private Villa",
    priceLabel: "₹5.10 Cr onwards",
    priceCr: 5.1,
    builtUpSqft: 3800,
    landSqft: 9600,
    bedrooms: 4,
    developer: "Deodar Habitats",
    status: "Under Construction",
    availability: "Possession indicated 2026",
    verified: true,
    verifications: ["Project Verified", "Developer Verified"],
    featured: false,
    lifestyle: ["Views", "Community", "Weekend escape"],
    amenities: ["Glazed pavilion", "Fireplace", "Cellar", "Concierge desk", "EV charging"],
    images: ["bungalow-exterior.jpg", "cat-mountains.jpg"],
    story: {
      idea: "A pavilion-plan villa among deodar, planned so the living volume can be opened entirely to the pines.",
      setting: "A gentle slope above Kasauli's cantonment, forty minutes from Chandigarh airport.",
      residence: "Four bedrooms over two levels with a glazed central pavilion and a stone cellar.",
      experience: "A short drive from the plains, with walks from the gate and a warm indoor winter.",
      community: "Sixteen residences sharing a small lounge, wellness room and estate staff.",
    },
    investment: { rentalNightly: 26000, occupancy: 32, appreciation: 8, lifestyleScore: 86, investmentScore: 82 },
  },
  {
    id: "the-cloud-house",
    name: "The Cloud House",
    location: "Dhanaulti",
    region: "Uttarakhand",
    neighbourhood: "dhanaulti",
    collection: "wellness",
    type: "Mountain Residence",
    priceLabel: "₹3.95 Cr onwards",
    priceCr: 3.95,
    builtUpSqft: 2900,
    landSqft: 7800,
    bedrooms: 3,
    developer: "Highline Retreats",
    status: "Ready",
    availability: "2 residences available",
    verified: false,
    verifications: ["Project Verified"],
    featured: false,
    lifestyle: ["Wellness", "Privacy", "Views"],
    amenities: ["Sauna", "Meditation deck", "Greenhouse", "Managed housekeeping"],
    images: ["prop-pool.jpg", "cat-wellness.jpg"],
    story: {
      idea: "A compact retreat at 2,200 metres, built for two people and occasional guests.",
      setting: "Above Dhanaulti's deodar belt, where cloud sits below the house for much of the year.",
      residence: "Three bedrooms, a sauna and a small glass greenhouse off the kitchen.",
      experience: "Cold, quiet and restorative. Ninety minutes from Dehradun airport.",
      community: "Seven residences with shared caretaking and a walking trail network.",
    },
    investment: { rentalNightly: 21000, occupancy: 29, appreciation: 8, lifestyleScore: 89, investmentScore: 76 },
  },
  {
    id: "the-orchard-residences",
    name: "The Orchard Residences",
    location: "Nainital",
    region: "Uttarakhand",
    neighbourhood: "mukteshwar",
    collection: "mountains",
    type: "Gated Community",
    priceLabel: "₹2.20 Cr onwards",
    priceCr: 2.2,
    builtUpSqft: 2100,
    landSqft: 4800,
    bedrooms: 2,
    developer: "Kumaon Land Partners",
    status: "Under Construction",
    availability: "Phase one open",
    verified: true,
    verifications: ["Project Verified", "Documentation Reviewed"],
    featured: false,
    lifestyle: ["Community", "Accessibility", "Rental potential"],
    amenities: ["Clubhouse", "Orchard walks", "Managed rental desk", "Security"],
    images: ["prop-living.jpg", "cat-mountains.jpg"],
    story: {
      idea: "An entry point into Kumaon ownership without compromising on siting or construction quality.",
      setting: "A south-facing orchard slope twenty minutes from Nainital lake.",
      residence: "Two-bedroom residences with private terraces and shared landscape.",
      experience: "Easy to reach, easy to maintain, and simple to let when unused.",
      community: "Thirty-four residences with a clubhouse and a managed rental programme.",
    },
    investment: { rentalNightly: 14000, occupancy: 38, appreciation: 9, lifestyleScore: 78, investmentScore: 85 },
  },
  {
    id: "the-walled-garden",
    name: "The Walled Garden",
    location: "Alwar",
    region: "Rajasthan",
    neighbourhood: "alwar",
    collection: "countryside",
    type: "Farmhouse",
    priceLabel: "₹2.60 Cr onwards",
    priceCr: 2.6,
    builtUpSqft: 3200,
    landSqft: 32000,
    bedrooms: 3,
    developer: "Sariska Country Estates",
    status: "Ready",
    availability: "4 parcels available",
    verified: true,
    verifications: ["Project Verified", "Developer Verified"],
    featured: false,
    lifestyle: ["Privacy", "Family", "Nature"],
    amenities: ["Walled garden", "Stepwell pool", "Courtyard", "Solar power", "Bore well"],
    images: ["bungalow-interior.jpg", "cat-country.jpg"],
    story: {
      idea: "A courtyard house behind a garden wall, on the approach to the Sariska landscape.",
      setting: "Semi-arid country with old trees, birdlife and long light.",
      residence: "Three bedrooms around a shaded courtyard with a stepped pool.",
      experience: "Winter breakfasts outdoors, safaris an hour away, and complete quiet at night.",
      community: "Nine parcels with shared security and water infrastructure.",
    },
    investment: { rentalNightly: 19000, occupancy: 28, appreciation: 7, lifestyleScore: 82, investmentScore: 74 },
  },
];

const DESTINATIONS = [
  {
    id: "jim-corbett", name: "Jim Corbett", epithet: "The Forest Edge", region: "Uttarakhand",
    collection: "forest", image: "cat-forest.jpg", drive: "5h 30m from Delhi NCR",
    lifestyle: "Forest living with genuine wilderness at the boundary — favoured by owners who want nature without altitude.",
    character: "Predominantly low-rise villas and small gated enclaves on wooded parcels, most between 8,000 and 20,000 sq ft.",
    market: "Steady owner-occupier demand with the strongest managed-rental performance among northern second-home markets.",
    connectivity: "Ramnagar railhead nearby; Pantnagar airport approximately 2h.",
    infrastructure: "Delhi–Dehradun and Kandi road upgrades are expected to shorten drive times.",
    fromCr: 4.75,
  },
  {
    id: "mukteshwar", name: "Mukteshwar", epithet: "The Quiet Mountain", region: "Uttarakhand",
    collection: "mountains", image: "cat-mountains.jpg", drive: "8h from Delhi NCR",
    lifestyle: "High, sparse and undramatic in the best way — chosen by buyers who value silence over social scenes.",
    character: "Independent houses on ridge plots, typically 4,000–10,000 sq ft with orchard land.",
    market: "Limited supply of well-titled ridge land keeps quality inventory scarce.",
    connectivity: "Kathgodam railhead approximately 2h; Pantnagar airport approximately 3h.",
    infrastructure: "Ongoing state road widening and improved water infrastructure in the belt.",
    fromCr: 2.2,
  },
  {
    id: "rishikesh", name: "Rishikesh", epithet: "The Wellness Valley", region: "Uttarakhand",
    collection: "wellness", image: "cat-wellness.jpg", drive: "5h from Delhi NCR",
    lifestyle: "River, practice and hospitality — the most service-oriented market in the region.",
    character: "Terraced estates and hospitality-managed residences above the valley.",
    market: "Wellness tourism supports both hospitality partnerships and owner rental participation.",
    connectivity: "Dehradun airport approximately 45m; Rishikesh railhead nearby.",
    infrastructure: "Expressway completion has materially reduced NCR drive times.",
    fromCr: 3.95,
  },
  {
    id: "kasauli", name: "Kasauli", epithet: "The Near Hill", region: "Himachal Pradesh",
    collection: "mountains", image: "bungalow-exterior.jpg", drive: "5h from Delhi NCR",
    lifestyle: "Cantonment calm with deodar walks and short travel time from the plains.",
    character: "Small villa communities and independent houses on gentle forested slopes.",
    market: "Mature market with tightly regulated construction and constrained new supply.",
    connectivity: "Chandigarh airport approximately 1h 30m.",
    infrastructure: "Kalka–Shimla corridor improvements underway.",
    fromCr: 5.1,
  },
  {
    id: "sohna", name: "Sohna", epithet: "The Weekend Country", region: "Haryana",
    collection: "countryside", image: "cat-country.jpg", drive: "1h 15m from Gurugram",
    lifestyle: "Close enough for a single night away; farmland, orchards and open sky.",
    character: "Acre-scale farm parcels with low country houses.",
    market: "Driven by proximity; land values track NCR infrastructure closely.",
    connectivity: "Delhi–Mumbai Expressway access; IGI airport approximately 1h 30m.",
    infrastructure: "Sohna elevated corridor and expressway interchanges now operational.",
    fromCr: 2.85,
  },
  {
    id: "alwar", name: "Alwar", epithet: "The Long Light", region: "Rajasthan",
    collection: "countryside", image: "bungalow-interior.jpg", drive: "3h from Delhi NCR",
    lifestyle: "Dry country, birdlife and heritage travel with Sariska within reach.",
    character: "Walled courtyard houses on large parcels, often with existing tree cover.",
    market: "Emerging; entry values remain low relative to hill destinations.",
    connectivity: "Expressway access; Jaipur airport approximately 2h 30m.",
    infrastructure: "Regional expressway and tourism circuit investment continuing.",
    fromCr: 2.6,
  },
  {
    id: "dhanaulti", name: "Dhanaulti", epithet: "The Cloud Line", region: "Uttarakhand",
    collection: "wellness", image: "prop-pool.jpg", drive: "6h 30m from Delhi NCR",
    lifestyle: "High-altitude quiet for restorative, low-density ownership.",
    character: "Compact retreats on deodar slopes, typically 2,000–4,000 sq ft.",
    market: "Small market with very limited titled land available.",
    connectivity: "Dehradun airport approximately 1h 30m.",
    infrastructure: "Mussoorie bypass works improving approach.",
    fromCr: 3.95,
  },
];

const COLLECTION_LABELS = {
  mountains: "The Mountains",
  forest: "The Forest",
  wellness: "The Wellness Escape",
  countryside: "The Weekend Country Home",
};

const LIFESTYLE_FACETS = ["Privacy", "Wellness", "Family", "Nature", "Views", "Community", "Hospitality", "Rental potential", "Accessibility", "Weekend escape"];

function getProperty(id) {
  return PROPERTIES.find((p) => p.id === id);
}
function getDestination(id) {
  return DESTINATIONS.find((d) => d.id === id);
}
function formatInr(value) {
  if (value >= 10000000) return `₹${(value / 10000000).toFixed(2)} Cr`;
  if (value >= 100000) return `₹${(value / 100000).toFixed(2)} L`;
  return `₹${Math.round(value).toLocaleString("en-IN")}`;
}
